#!/usr/bin/env python3
"""Generate a sample-gallery Markdown file for every content domain.

Usage (from anywhere):
    python scripts/generate_samples.py

Writes SAMPLES.md at the project root and prints a one-line summary.
Works in mock mode (no API keys required) and automatically uses a real
provider when keys are present in the environment / .env file.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# ── Ensure project root is importable ────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# ── Per-domain example topics (nice human-readable seeds) ────────────────────
EXAMPLE_TOPICS: dict[str, str] = {
    "social":  "Launching an AI-powered journaling app that helps you reflect daily",
    "product": "Ergonomic standing desk mat with anti-fatigue gel core and beveled edges",
    "email":   "Flash sale: 30% off our annual productivity subscription — 24 hours only",
    "resume":  "Migrated a Django monolith to microservices, cutting p95 latency 60%",
    "blog":    "How to build a second brain with open-source tools and zero subscription fees",
    "video":   "Three Python tricks that senior engineers use but never talk about",
}

DEFAULT_TOPIC = "AI-powered tools for modern creators and builders"


def _render_field(value: object) -> str:
    """Render a single field value as a plain string."""
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    return str(value) if value is not None else ""


def build_gallery(output_path: str | None = None) -> str:
    """Generate one sample per domain and return the full Markdown string.

    Args:
        output_path: If provided, the Markdown is also written to this path.

    Returns:
        The rendered Markdown as a string.
    """
    # Late imports so the module can be imported cheaply in tests without
    # triggering dotenv / heavy package loading at import time.
    from src.config import Config
    from src.domains import list_domains
    from src.generator import ContentGenerator, ContentRequest
    from src.vector_store import MemoryVectorStore

    # ── Config & provider ─────────────────────────────────────────────────
    cfg = Config.from_env()
    provider = cfg.resolved_provider()

    # ── Vector store seeded from knowledge/examples.json ─────────────────
    vs = MemoryVectorStore(embed_model=cfg.embed_model)
    examples_file = PROJECT_ROOT / "knowledge" / "examples.json"
    if examples_file.exists():
        with open(examples_file, encoding="utf-8") as fh:
            vs.add_many(json.load(fh))

    generator = ContentGenerator(cfg, vector_store=vs)

    # ── Build Markdown ────────────────────────────────────────────────────
    lines: list[str] = [
        "# AI Content Studio — Sample Gallery",
        "",
        f"> Generated by provider: **{provider}**",
        "",
    ]

    domains = list_domains()
    for domain in domains:
        topic = EXAMPLE_TOPICS.get(domain.key, DEFAULT_TOPIC)
        channel = domain.channels[0] if domain.channels else ""

        req = ContentRequest(
            domain=domain.key,
            topic=topic,
            channel=channel,
            tone="professional",
            num_items=1,
            use_rag=True,
        )
        items = generator.generate(req)

        # Domain heading
        lines.append(f"## {domain.label}")
        lines.append("")
        lines.append(f"**Topic:** {topic}")
        if channel:
            lines.append(f"**Channel:** {channel}")
        lines.append("")

        if not items:
            lines.append("_No output generated._")
            lines.append("")
            continue

        # Render the first (and only) item's fields
        item = items[0]
        for field_name in domain.output_fields:
            value = item.fields.get(field_name, "")
            rendered = _render_field(value)
            lines.append(f"**{field_name}:** {rendered}")
        lines.append("")

        # Optional brand-match score
        if item.brand_match is not None:
            lines.append(f"_Brand match score: {item.brand_match}_")
            lines.append("")

    markdown = "\n".join(lines)

    # ── Write file if requested ────────────────────────────────────────────
    if output_path is not None:
        Path(output_path).write_text(markdown, encoding="utf-8")

    return markdown


def main() -> None:
    """Entry point: write SAMPLES.md at the project root and exit 0."""
    out = PROJECT_ROOT / "SAMPLES.md"
    markdown = build_gallery(output_path=str(out))

    domain_count = markdown.count("\n## ")
    print(
        f"Wrote {out} — {domain_count} domain(s), "
        f"{len(markdown)} chars"
    )
    sys.exit(0)


if __name__ == "__main__":
    main()
